// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// expcorrectC
NumericMatrix expcorrectC(NumericMatrix mat, NumericVector diffdate, double lambda);
RcppExport SEXP _PheVis_expcorrectC(SEXP matSEXP, SEXP diffdateSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type diffdate(diffdateSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(expcorrectC(mat, diffdate, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PheVis_expcorrectC", (DL_FUNC) &_PheVis_expcorrectC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_PheVis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
