# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' expcorrectC
#' @title expcorrectC
#' @description c++ function to compute exponential cumulation of information.
#'
#' @param mat A matrix where each column is a variable to be cumulated.
#' @param diffdate Number of days between each sojourn. NA for switch of patient and restart cumulation.
#' @param lambda A double to set the exponential cumulation.
#' 
#' @return A matrix corresponding to the mat argument with cumulated exponential decay
#' 
expcorrectC <- function(mat, diffdate, lambda) {
    .Call('_PheVis_expcorrectC', PACKAGE = 'PheVis', mat, diffdate, lambda)
}

